# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bharat Kunduri
tagline:          'Personal Blog'
description:      'A blog I use to share some of my projects and discuss about projects I come across.'
url:              
baseurl:          /

author:
  name:           'Bharat Kunduri'
  url:            

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bharatreddy

linkedin:
  prfl:           http://www.linkedin.com/pub/bharat-kunduri/64/14a/9a0/

emails:
  vt:             mailto:bharatr@vt.edu
  personal:       mailto:redbharat@gmail.com