# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bharat Kunduri
tagline:          'Personal Blog'
description:      'A blog I use to share some of my projects and discuss about projects I come across.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bharatreddy

linkedin:
  prfl:           http://www.linkedin.com/pub/bharat-kunduri/64/14a/9a0/